config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :mailings
  resources :bookers
  resources :events, only: [:index, :new, :destroy,:edit, :update]
  post "events/create", to: "events#create", as: :create_event
  get "event/search/", to: "events#search"
  namespace :events do
    get "export_kalender", to: "export#show"
    post "export_kalender_and_send", to: "export#export_and_send", as: :export_and_send_events
  end
  get 'bands/edit'
  post 'kontaktanfrage', to: "contact#mailing", as: :contact_mailing
  devise_for :admins
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  post 'mailings/mailing', to: 'mailings#mailing'

  patch 'bookers/update/:id', to: 'bookers#update'

  get 'charts/email_null', to: 'charts#email_null', as: :email_null_charts
  get 'charts/email_to_booker', to: 'charts#email_to_booker', as: :email_to_booker_charts

  get "dashboard", to: "dashboard#index", as: :dashboard
  get "/", to: "landing_page#index"
  resources :users
  resources :bands
  post "bands_share", to: "bands#share", as: :band_share
  get "news/index", to: "news#index"
  get "bands/which_edit", to: "bands#which_edit", as: :bands_which_edit
  get "calendar", to: "events#calendar", as: :calendar
  get "not_active", to: "landing_page#not_active"
  get "not_confirmed", to: "landing_page#not_confirmed"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # match '*path', to: redirect('/'), via: :all
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :user_bands
  has_many :users, through: :user_bands

  has_many :event
  validates :name, length: { minimum: 2}
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  before_save :set_color

  private

  def set_color
    if self.event_color.blank?
      self.band_color = "#000"
    end
  end

end

app/models/booker.rb
class Booker < ApplicationRecord
  belongs_to :user
  has_many :audit_table_for_Bookers
  after_update :save_to_audit_after
  validates :stadt, presence: true;
  validates :club, presence: true;
  validates :email, presence: true;
  validates :land, presence: true;

  def save_to_audit_before
    @audit = AuditTableForBookers.new
    @audit.stadt_old = self.stadt
    @audit.club_old = self.club
    @audit.homepage_old = self.homepage
    @audit.email_old = self.email
    @audit.telefon_old = self.telefon
    @audit.bundesland_old = self.bundesland
    @audit.land_old = self.land
    @audit.plz_old = self.plz
    @audit.active_old = self.active
    @audit.booker_id = self.id
    @audit.user_id = self.user_id
    if self.active == false
      @audit.action = 'Delete'
      @audit.kommentar = self.kommentar
    end
    @audit.save!
  end
  private

  def save_to_audit_after
    @audit = AuditTableForBookers.last
    @audit.stadt_new = self.stadt
    @audit.club_new = self.club
    @audit.homepage_new = self.homepage
    @audit.email_new = self.email
    @audit.telefon_new = self.telefon
    @audit.bundesland_new = self.bundesland
    @audit.land_new = self.land
    @audit.plz_new = self.plz
    @audit.active_new = self.active
    @audit.save
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :band
end

app/models/mailing.rb
class Mailing < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  validates :subject, presence: true
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :user_bands
  has_many :bands, through: :user_bands
  has_many :mailings
  has_many :bookers

  def is_admin?
    self.admin
  end
end

app/models/user_band.rb
class UserBand < ApplicationRecord
  belongs_to :user
  belongs_to :band
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :logged_in
  def new
    @band = Band.new
  end

  def show
    @band = Band.where("id IN (SELECT band_id FROM user_bands WHERE user_id = #{current_user.id})")
  end

  def index
    @band = Band.where("id IN (SELECT band_id FROM user_bands WHERE user_id = #{current_user.id})")
  end

  def create
    @band = Band.new(band_params)
    @band.user_id = current_user.id
    if @band.save!
      ub = UserBand.new(user_id: current_user.id, band_id: @band.id)
      ub.save
      redirect_to dashboard_path, flash: { notice: "Deine Band wurde erstellt" }
    else
      redirect_to dashboard_path, flash: { notice: "Deine Band konnte nicht erstellt werden" }
    end
  end

  def edit
    @band = Band.find(params[:id])
    @users = User.where("active IS NOT NULL OR active != false")
  end

  def update
    @band = Band.find(band_params[:id])
    if @band.update(band_params)
      redirect_to dashboard_path, flash: { notice: "Deine Band wurde geupdated" }
    else
      redirect_to dashboard_path, flash: { notice: "Deine Band konnte nicht geupdated werden" }
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to dashboard_path
  end

  def share
    u = UserBand.new(user_id: params[:band_share][:user], band_id:  params[:band_share][:band_id])
    if u.save
      redirect_to dashboard_path, flash: { notice: "Band wurde geteilt" }
    else
      redirect_to dashboard_path, flash: { error: "Band konnte nicht geteilt werden" }
    end
  end

  private
  def band_params
    params.require(:band).permit(:id,:name, :ort, :bandcamp, :website, :gründung, :email, :telefon, :event_color)
  end
  protected

  def logged_in
    redirect_to "/" unless user_signed_in?
  end

end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :logged_in
  def email_null
    @hash = { }
    null = Booker.where('Email IS NULL AND active = true').count
    not_null = Booker.where('Email IS NOT NULL AND active = true').count
    @hash['Ohne E-Mail'] = null
    @hash['Mit E-Mail'] = not_null
    render json: @hash
  end

  def email_to_booker
    @hash = { }
    anzahl = 0
    created_tmp = ''
    Mailing.select(:veranstalter, :created_at).each do |mail|
      if created_tmp == Time.at(mail.created_at).to_date
        anzahl += mail.veranstalter.count
      else
        anzahl = mail.veranstalter.count
      end
      created = Time.at(mail.created_at).to_date
      created_tmp = Time.at(mail.created_at).to_date
      @hash[created] = anzahl
    end
    render json: @hash

  end

  protected

  def logged_in
    redirect_to "/" unless user_signed_in?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :logged_in
  before_action :activated
  before_action :check_for_mobile, :only => [:index]

  def index
  end

  private
  protected

  def logged_in
    redirect_to "/" unless current_user
  end

  def activated
    unless current_user.active
      destroy_user_session
      redirect_to "/not_active"
    end
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :logged_in
  def index
    sql = "SELECT club, email, stadt, bundesland FROM Bookers WHERE email IN (SELECT email FROM Bookers GROUP BY email, active HAVING COUNT(email) >= 2 AND email IS NOT NULL AND NOT (active = false OR active IS NULL )) AND NOT (active IS NULL OR active =  'false') ORDER BY email, club, stadt;"

    @booker_to_edit = ActiveRecord::Base.connection.execute(sql)

    @news = News.all.order(created_at: :desc)
  end
  protected

  def logged_in
    redirect_to "/" unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/bookers_helper.rb
module BookersHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/mailings_helper.rb
module MailingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/actions/_contact.html.slim
.modal.fade.bd-example-modal-lg.kontaktanfrage_modal aria-hidden="true" aria-labelledby="myLargeModalLabel" role="dialog" tabindex="-1"
  .modal-dialog.modal-lg.modal-dialog-centered
    .modal-content style="background-color: white"
      .modal-body style="overflow:auto; background-color: #FF9800"
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        = render "contact/index"

app/views/dashboard/actions/_einstellungen.html.slim
.modal.fade.bd-example-modal-lg.einstellungen_modal aria-hidden="true" aria-labelledby="myLargeModalLabel" role="dialog" tabindex="-1"
  .modal-dialog.modal-lg.modal-dialog-centered
    .modal-content style="background-color: #739eb7;"
      .modal-body style="height: 600px; overflow: auto;"
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        .text-center
					.btn-group.btn-group-toggle data-toggle="buttons"
						label.btn.btn-secondary.nutzer
							input#option1 autocomplete="off" checked="" name="options" type="radio" Nutzereinstellungen
						label.btn.btn-secondary.band-bearbeiten
							input#option2 autocomplete="off" name="options" type="radio" Bandeinstellungen
						label.btn.btn-secondary.band-create
							input#option2 autocomplete="off" name="options" type="radio" Band hinzufügen
        .js-lazy-load-einstellungen-user
        .js-lazy-load-einstellungen-band-bearbeiten
        .js-lazy-load-einstellungen-band-create
        .einstellungen-description
          .text-band-edit-description
            .card
              .card-body
                .card-title
                  h4
                    | Ändere deine Nutzereinstellungen, füge eine neue Band hinzu oder pass eine bestehende an
                p
                  | Je mehr Informationen wir über deine Band haben, desto mehr wird dem Veranstalter angezeigt
                p
                  | Es wäre auch gut, wenn du in die News schauen würdest. So kannst du z.B. erfahren, dass noch einige E-Mails doppelt vergeben sind und die Veranstalter so unnötig oft angeschrieben werden.
                b
                  | So wäre es sehr hilfreich, wenn du deinen Teil beitragen könntest und diese Veranstalter löschst und neue hinzufügst.

            .card-img-bottom
              = image_tag("main_einstellungen", class: "card-img-bottom")

        //#einstellungen

javascript:
  $('.nutzer').click(function(){
		$('.js-lazy-load-einstellungen-user').load("/users/edit");
		$('.js-lazy-load-einstellungen-band-bearbeiten').hide();
		$('.js-lazy-load-einstellungen-band-create').hide();
		$('.js-lazy-load-einstellungen-user').show();
		$('.einstellungen-description').hide();
	})
  $('.band-bearbeiten').click(function(){
		$('.js-lazy-load-einstellungen-band-bearbeiten').load("/bands/which_edit")
		$('.js-lazy-load-einstellungen-user').hide();
		$('.js-lazy-load-einstellungen-band-create').hide();
		$('.js-lazy-load-einstellungen-band-bearbeiten').show();
		$('.einstellungen-description').hide();
	})
  $('.band-create').click(function(){
		$('.js-lazy-load-einstellungen-band-create').load("/bands/new")
		$('.js-lazy-load-einstellungen-user').hide();
		$('.js-lazy-load-einstellungen-band-bearbeiten').hide();
		$('.js-lazy-load-einstellungen-band-create').show();
		$('.einstellungen-description').hide();
	})

app/views/dashboard/actions/_history.html.slim
.modal.fade.bd-example-modal-lg.history_modal aria-hidden="true" aria-labelledby="myLargeModalLabel" role="dialog" tabindex="-1"
  .modal-dialog.modal-lg.modal-dialog-centered
    .modal-content style="background-color: #59b8c6;"
      .modal-body
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        p
          | heyyy, hier wird ziemlich viel content stehen. lool
        h3
          | alles mögliche z.B.
        b
          | alle Konzertveranstalter

app/views/dashboard/actions/_kalender.html.slim
.modal.fade.bd-example-modal-lg.kalender_modal aria-hidden="true" aria-labelledby="myLargeModalLabel" role="dialog"
  .modal-dialog.modal-lg.modal-dialog-centered
    .modal-content style="background-color: #e2446e;"
      .modal-body style="overflow: auto; height: 600px;"
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        br
        .js-lazy-loader-calendar style="color: white;"
          = render "events/calendar"
javascript:
  $('#calendar').fullCalendar({
    events: '/events.json'
  });

app/views/dashboard/actions/_kontakte.html.slim
.modal.fade.bd-example-modal-lg.kontakte_modal aria-hidden="true" aria-labelledby="myLargeModalLabel" role="dialog"
  #veranstalter-modal.modal-dialog.modal-lg.modal-dialog-centered
    .modal-content style="background-color: #0bc443;"
      .modal-body style="max-height: 800px; overflow:auto;"
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        #kontakte

app/views/dashboard/actions/_likes.html.slim
.modal.fade.bd-example-modal-lg.likes_modal aria-hidden="true" aria-labelledby="myLargeModalLabel" role="dialog" tabindex="-1"
  .modal-dialog.modal-lg.modal-dialog-centered
    .modal-content style="background-color: #e2446e;"
      .modal-body
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        p
          | heyyy, hier wird ziemlich viel content stehen. lool
        h3
          | alles mögliche z.B.
        b
          | alle Konzertveranstalter

app/views/dashboard/actions/_nachrichten.html.slim
.modal.fade.bd-example-modal-lg.nachrichten_modal aria-hidden="true" aria-labelledby="myLargeModalLabel" role="dialog" tabindex="-1"
  #mailing-modal.modal-dialog.modal-lg.modal-dialog-centered
    .modal-content style="background-color: #f7973d;"
      .modal-body
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        #nachrichten

app/views/dashboard/actions/_news.html.slim
.modal.fade.bd-example-modal-lg.news_modal aria-hidden="true" aria-labelledby="myLargeModalLabel" role="dialog" tabindex="-1"
  .modal-dialog.modal-lg.modal-dialog-centered
    .modal-content style="background-color: smokewhite;"
      .modal-body style="overflow:auto; height: 600px;"
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;

        .js-lazy-loader-news

app/views/dashboard/actions/_statistiken.html.slim
.modal.fade.bd-example-modal-lg.statistiken_modal aria-hidden="true" aria-labelledby="myLargeModalLabel" role="dialog" tabindex="-1"
  .modal-dialog.modal-lg.modal-dialog-centered
    .modal-content style="background-color: #59b8c6;"
      .modal-body style="overflow:auto; height: 600px;"
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;

        .statistiken_charts
          .card
            .card-body
              .card-title
                .text-center
                  h4
                    | Veranstalter ohne E-Mail
              = pie_chart email_null_charts_path
              small
                | Bitte unbedingt die E-Mails der Veranstalter nachtragen. Je mehr E-Mails eingetragen sind, desto mehr können erreicht werden. Dazu gerne in die News schauen.
          .card
            .card-body
              .card-title
                .text-center
                  h4
                    | Veranstalter zuletzt angelegt
              = area_chart Booker.where('created_at IS NOT NULL').group('DATE(created_at)').count
          .card
            .card-body
              .card-title
                .text-center
                  h4
                    | Nachrichten-Tool pro Tag in Nutzung
              = bar_chart Mailing.where('created_at IS NOT NULL').group('DATE(created_at)').count
          .card
            .card-body
              .card-title
                .text-center
                  h4
                    | Versandte E-Mails pro Tag
              = column_chart email_to_booker_charts_path
          .card
            .card-body
              .card-title
                .text-center
                  h4
                    | Veranstalter nach Bundesland
              = pie_chart Booker.where('bundesland IS NOT NULL AND active = true').group(:bundesland).count, donut: true, height: "400px"
          .card
            .card-body
              .card-title
                .text-center
                  h4
                    | Veranstalter nach Land
              = pie_chart Booker.where('land IS NOT NULL AND active = true').group(:land).count, donut: true, height: "400px"

app/views/dashboard/index.html.slim
header
  ul.breadcrumbs
    li.news data-toggle="modal" data-target=".news_modal"
      p.d-inline style="color: #606770" News
    li.contact data-toggle="modal" data-target=".kontaktanfrage_modal"
      p.d-inline style="color: #606770" Kontakt
    li
      = link_to "Logout", destroy_user_session_path(current_user), method: :delete

.content
  .caption
    h1 Kontaktiere
    h1 Konzertveranstalter
    span.city aus der ganzen
    span.country Welt
  .text-center
    - flash.each do |key, value|
      = content_tag :div, value, class: "flash_#{key}"
  nav.main-nav
    ul
      li.veranstalter data-toggle="modal" data-target=".kontakte_modal"
        .icon.fa.fa-address-book.fa-2x
        span Veranstalter
      li.mailings data-toggle="modal" data-target=".nachrichten_modal"
        .icon.fa.fa-envelope.fa-2x
        span Nachrichten
      li.statistiken data-toggle="modal" data-target=".statistiken_modal"
        .icon.fa.fa-align-left.fa-2x
        span Statistiken
      li.kalender data-toggle="modal" data-target=".kalender_modal"
        .icon.fa.fa-calendar.fa-2x
        span Kalender
      li.settings data-toggle="modal" data-target=".einstellungen_modal"
        /*.menuicon.fa.fa-bars
            .ul-menu
            p Settings
            ul
              li Option 1
              li Option 2
              li Option 3
            input max="100" min="0" onchange="rangevalue.value=value" type="range" /
            output#rangevalue 50
            button Save Changes
            .ul-menu-close.fa.fa-times
        .icon.fa.fa-cog.fa-2x
        span Einstellungen

= render 'dashboard/actions/kontakte'
= render 'dashboard/actions/nachrichten'
= render 'dashboard/actions/statistiken'
= render 'dashboard/actions/kalender'
= render 'dashboard/actions/einstellungen'
= render 'dashboard/actions/news'
= render 'dashboard/actions/contact'

javascript:
  $('.main-nav ul li').click(function() {
  $('.main-nav ul li').removeClass('active');
  $(this).addClass('active');
  });

  $('.menuicon').click(function() {
    $('.ul-menu').css('bottom', '-150%');
    $(this).next('.ul-menu').css('bottom', '0');
  });

  $('.ul-menu-close').click(function() {
    $('.ul-menu').css('bottom', '-150%');
  });

  $('.flash_notice').fadeOut(5000);
  $('.flash_error').fadeOut(5000);