config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :mailings
  resources :bookers
  resources :events, only: [:index, :new, :destroy,:edit, :update]
  post "events/create", to: "events#create", as: :create_event
  get "event/search/", to: "events#search"
  namespace :events do
    get "export_kalender", to: "export#show"
    post "export_kalender_and_send", to: "export#export_and_send", as: :export_and_send_events
  end
  get 'bands/edit'
  post 'kontaktanfrage', to: "contact#mailing", as: :contact_mailing
  devise_for :admins
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  post 'mailings/mailing', to: 'mailings#mailing'

  patch 'bookers/update/:id', to: 'bookers#update'

  get 'charts/email_null', to: 'charts#email_null', as: :email_null_charts
  get 'charts/email_to_booker', to: 'charts#email_to_booker', as: :email_to_booker_charts

  get "dashboard", to: "dashboard#index", as: :dashboard
  get "/", to: "landing_page#index"
  resources :users
  resources :bands
  post "bands_share", to: "bands#share", as: :band_share
  get "news/index", to: "news#index"
  get "bands/which_edit", to: "bands#which_edit", as: :bands_which_edit
  get "calendar", to: "events#calendar", as: :calendar
  get "not_active", to: "landing_page#not_active"
  get "not_confirmed", to: "landing_page#not_confirmed"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # match '*path', to: redirect('/'), via: :all
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :band
end

app/controllers/events/export_controller.rb
class Events::ExportController < ApplicationController
  def show
    @bands = Band.where("id IN (SELECT band_id FROM user_bands WHERE user_id = #{current_user.id})")
  end

  def export_and_send
    if params[:export][:events].blank?
      @events = Event.where("band_id IN (SELECT band_id FROM user_bands WHERE user_id = #{current_user.id}) AND start_time >= ? ", Time.zone.now)
    else
      @events = Event.where("band_id IN (SELECT band_id FROM user_bands WHERE user_id = #{current_user.id}) AND band_id = #{params[:export][:events]} AND start_time >= ? ", Time.zone.now)
    end
    if EventMailer.send_events(@events, current_user).deliver_now
      redirect_to dashboard_path, flash: { notice: "Events wurden verschickt" }
    else
      redirect_to dashboard_path, flash: { error: "Die Events konnten nicht verschickt werden..." }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :logged_in

  # GET /events
  # GET /events.json
  def index
    @events = Event.where("band_id IN (SELECT band_id FROM user_bands WHERE user_id = #{current_user.id})")
    # @events = Event.where(band_id: Band.where(user_id: current_user.id))
    @events = @events.where('start_time >= ? ', Time.zone.now).order("start_time")
    @band = Band.where("id IN (SELECT band_id FROM user_bands WHERE user_id = #{current_user.id})")
  end

  def search
    if params[:band_id].blank?
      @events = Event.where("band_id IN (SELECT band_id FROM user_bands WHERE user_id = #{current_user.id})")
      # @events = Event.where(band_id: Band.where(user_id: current_user.id))
      @events = @events.where('start_time >= ? ', Time.zone.now)
    else
      @events = Event.where('start_time >= ? AND band_id = ?', Time.zone.now, params[:band_id])
    end
    respond_to do |f|
      f.js
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  def calendar
    respond_to do |format|
      format.js
    end
  end

  # GET /events/new
  def new
    @event = Event.new
    @band = Band.where("id IN (SELECT band_id FROM user_bands WHERE user_id = #{current_user.id})")
  end

  # GET /events/1/edit
  def edit
    respond_to do |format|
      format.js
    end
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.band_id = params[:event][:band_id]
    if @event.save
      respond_to do |format|
        format.js {
          render 'calendar'
        }
      end
    end

    #respond_to do |format|
    #  if @event.save
    #    format.html { render 'calendar'}
    #    format.json { render :show, status: :created, location: @event }
    #  else
    #    format.html { render :new }
    #    format.json { render json: @event.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    if @event.update(event_params)
      respond_to do |format|
        format.js {
          render 'calendar'
        }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :start_time, :end_time, :location, :bands, :link)
    end
  protected
  def logged_in
    redirect_to "/" unless user_signed_in?
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_calendar.html.slim
#calendar
br
.text-center
  button.new-concert style= "margin-right: 10px;" class="btn btn-secondary"
    | Neues Konzert anlegen
  button.all-concerts style= "margin-right: 10px;" class="btn btn-secondary"
    | Alle Konzerte auflisten
  button.export-concerts style= "margin-right: 10px;" class="btn btn-secondary"
    | Kalender exportieren

javascript:
  $('#calendar').fullCalendar({
    events: '/events.json',
    eventClick: function(calEvent, jsEvent, view) {
      alert('Event: ' + calEvent.title +
        '\nBeschreibung: ' + calEvent.description +
        '\nOrt: ' + calEvent.location +
        '\nVeranstaltung: ' + calEvent.link +
        '\nBand: ' + calEvent.band
        );
      if (calEvent.url){
        return false;
        }
      }
  });

app/views/events/_edit.html.slim
= simple_form_for @event, url: event_path(format: :js),method: :put, remote: true do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .text-event-edit-description
    .card
      .card-body
        .card-title
          h4
            | Kalendereintrag erstellen
        .form-inputs
          .custom_event_form
            .input-event-form-group
                i.fa.fa-user.fa-2x
                = f.input :title, label: false, placeholder: "Name der Veranstaltung"
            .input-event-form-group
                i.fa.fa-align-left.fa-2x
                = f.input :description, label: false, placeholder: "Beschreibung der Veranstaltung"
            .input-event-form-group
                i.fa.fa-map-marker.fa-2x
                = f.input :location, label: "Ort", label: false, placeholder: "Ort der Veranstaltung"
            .input-event-form-group
                i.fa.fa-sign-language.fa-2x
                = f.input :bands, label: false, placeholder: "Teilnehmende Bands"
            .input-event-form-group
                i.fa.fa-link.fa-2x
                = f.input :link, label: false, placeholder: "Link zur Veranstaltung"
            .input-event-form-group
                i.fa.fa-calendar.fa-2x
                = f.input :start_time,as: :date, html5: true, label: false,hint: "Wann findet das Konzert statt?"
      .card-footer
        .text-center
          = f.button :submit, "Ändere Kalendereintrag", class: "btn btn-secondary"

br
.text-center
  button.all-concerts style= "margin-right: 10px;" class="btn btn-secondary"
    | Alle Konzerte auflisten
  = link_to "Kalender", calendar_path, remote: true, class: "btn btn-secondary"

app/views/events/_form.html.slim
= simple_form_for(@event) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :description, label: "Beschreibung"
    = f.input :location, label: "Ort"
    = f.input :bands
    = f.input :link, label: "Link zur Veranstaltung"
    = f.input :start_time

  .text-center
    = f.button :submit, class: "btn btn-secondary", url: calendar_path, remote: true

app/views/events/_index.html.slim
.row
  .col.col-lg-12
    table.table.table-striped.all_concerts.table-responsive-sm style="color: black; background-color: whitesmoke "
      thead
        tr
          th Name
          th Ort
          th Beschreibung
          th Bands
          th Datum
          th
          th

      tbody
        - @events.each do |event|
          tr
            td = event.title
            td = event.location
            td = event.description
            th = event.bands
            td = event.start_time.strftime("%d.%m.%Y")
            td = link_to 'Anzeigen', edit_event_path(event), class: "btn btn-success", remote: true
            td = link_to 'Löschen', event, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger", remote: true

app/views/events/calendar.js.erb
$('.js-lazy-loader-calendar').html("<%= escape_javascript(render :partial => 'calendar') %>");

app/views/events/create.js.erb
$('.js-lazy-loader-calendar').html("<%= escape_javascript(render :partial => 'calendar') %>");

app/views/events/destroy.js.erb
$(".js-lazy-loader-calendar").html("<%= escape_javascript( render :partial => "calendar" )  %>");

app/views/events/edit.js.erb
$(".js-lazy-loader-calendar").html("<%= escape_javascript( render :partial => "edit" )  %>");

app/views/events/index.html.slim
p.d-inline Alle zukünftigen Konzerte von: #{" "}
= simple_form_for :event, url: {action: "search"}, remote: true do |f|
  h4 = f.input :bands,  collection: @band, id: "select-band-for-filtering-concerts", label: false

.js-lazy-loader-specific-concerts
  = render 'index', locales: {event: @events}
br

.text-center
  button.new-concert style= "margin-right: 10px;" class="btn btn-secondary"
    | Neues Konzert anlegen
  = link_to "Kalender", calendar_path, remote: true, class: "btn btn-secondary"

app/views/events/new.html.slim
= simple_form_for @event, url: create_event_path(format: :js), remote: true do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .text-event-edit-description
    .card
      .card-body
        .card-title
          h4
            | Kalendereintrag erstellen
        .form-inputs
          = f.input :band_id, collection: @band, include_blank: false, include_hidden: false, label: "Für welche Band?"
          .custom_event_form
            .input-event-form-group
                i.fa.fa-user.fa-2x
                = f.input :title, label: false, placeholder: "Name der Veranstaltung"
            .input-event-form-group
                i.fa.fa-align-left.fa-2x
                = f.input :description, label: false, placeholder: "Beschreibung der Veranstaltung"
            .input-event-form-group
                i.fa.fa-map-marker.fa-2x
                = f.input :location, label: "Ort", label: false, placeholder: "Ort der Veranstaltung"
            .input-event-form-group
                i.fa.fa-sign-language.fa-2x
                = f.input :bands, label: false, placeholder: "Teilnehmende Bands"
            .input-event-form-group
                i.fa.fa-link.fa-2x
                = f.input :link, label: false, placeholder: "Link zur Veranstaltung"
            .input-event-form-group
                i.fa.fa-calendar.fa-2x
                = f.input :start_time,as: :date, html5: true, label: false,hint: "Wann findet das Konzert statt?"
      .card-footer
        .text-center
          = f.button :submit, "Erstelle Kalendereintrag", class: "btn btn-secondary"

br
.text-center
  button.all-concerts style= "margin-right: 10px;" class="btn btn-secondary"
    | Alle Konzerte auflisten
  = link_to "Kalender", calendar_path, remote: true, class: "btn btn-secondary"

app/views/events/search.js.erb
$(".js-lazy-loader-specific-concerts").html("<%= escape_javascript( render(partial: "index") ) %>");