config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :mailings
  resources :bookers
  resources :events, only: [:index, :new, :destroy,:edit, :update]
  post "events/create", to: "events#create", as: :create_event
  get "event/search/", to: "events#search"
  namespace :events do
    get "export_kalender", to: "export#show"
    post "export_kalender_and_send", to: "export#export_and_send", as: :export_and_send_events
  end
  get 'bands/edit'
  post 'kontaktanfrage', to: "contact#mailing", as: :contact_mailing
  devise_for :admins
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  post 'mailings/mailing', to: 'mailings#mailing'

  patch 'bookers/update/:id', to: 'bookers#update'

  get 'charts/email_null', to: 'charts#email_null', as: :email_null_charts
  get 'charts/email_to_booker', to: 'charts#email_to_booker', as: :email_to_booker_charts

  get "dashboard", to: "dashboard#index", as: :dashboard
  get "/", to: "landing_page#index"
  resources :users
  resources :bands
  post "bands_share", to: "bands#share", as: :band_share
  get "news/index", to: "news#index"
  get "bands/which_edit", to: "bands#which_edit", as: :bands_which_edit
  get "calendar", to: "events#calendar", as: :calendar
  get "not_active", to: "landing_page#not_active"
  get "not_confirmed", to: "landing_page#not_confirmed"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # match '*path', to: redirect('/'), via: :all
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :user_bands
  has_many :users, through: :user_bands

  has_many :event
  validates :name, length: { minimum: 2}
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  before_save :set_color

  private

  def set_color
    if self.event_color.blank?
      self.band_color = "#000"
    end
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :logged_in
  def new
    @band = Band.new
  end

  def show
    @band = Band.where("id IN (SELECT band_id FROM user_bands WHERE user_id = #{current_user.id})")
  end

  def index
    @band = Band.where("id IN (SELECT band_id FROM user_bands WHERE user_id = #{current_user.id})")
  end

  def create
    @band = Band.new(band_params)
    @band.user_id = current_user.id
    if @band.save!
      ub = UserBand.new(user_id: current_user.id, band_id: @band.id)
      ub.save
      redirect_to dashboard_path, flash: { notice: "Deine Band wurde erstellt" }
    else
      redirect_to dashboard_path, flash: { notice: "Deine Band konnte nicht erstellt werden" }
    end
  end

  def edit
    @band = Band.find(params[:id])
    @users = User.where("active IS NOT NULL OR active != false")
  end

  def update
    @band = Band.find(band_params[:id])
    if @band.update(band_params)
      redirect_to dashboard_path, flash: { notice: "Deine Band wurde geupdated" }
    else
      redirect_to dashboard_path, flash: { notice: "Deine Band konnte nicht geupdated werden" }
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to dashboard_path
  end

  def share
    u = UserBand.new(user_id: params[:band_share][:user], band_id:  params[:band_share][:band_id])
    if u.save
      redirect_to dashboard_path, flash: { notice: "Band wurde geteilt" }
    else
      redirect_to dashboard_path, flash: { error: "Band konnte nicht geteilt werden" }
    end
  end

  private
  def band_params
    params.require(:band).permit(:id,:name, :ort, :bandcamp, :website, :gründung, :email, :telefon, :event_color)
  end
  protected

  def logged_in
    redirect_to "/" unless user_signed_in?
  end

end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/edit.html.slim
.settings
  .text-band-edit-description style="margin-top: 2%"
    .card
      .card-body
        = simple_form_for @band do |f|
            .custom_band_form
              .input-band-form-group
                i.fa.fa-user.fa-2x
                = f.input_field :name, required: true, placeholder: "Name", input_html: { required: true }, class: "band_name"
              .input-band-form-group
                i.fa.fa-map-marker.fa-2x
                = f.input_field :ort, placeholder: "Von wo kommt ihr her?"
              .input-band-form-group
                i.fa.fa-headphones.fa-2x
                = f.input_field :bandcamp, placeholder: "Bandcamp Link"
              .input-band-form-group
                i.fa.fa-home.fa-2x
                = f.input_field :website, placeholder: "Eure Website"
              .input-band-form-group
                i.fa.fa-envelope.fa-2x
                = f.input_field :email, required: true, placeholder: "Eure Band E-mail"
              .input-band-form-group
                i.fa.fa-phone.fa-2x
                = f.input_field :telefon, placeholder: "Telefon"
              .input-band-form-group
                i.fa.fa-birthday-cake.fa-2x
                = f.input :gründung, as: :date, html5: :true, label: false, hint: "Seit wann gibt es eure Band?"
              .input-band-form-group
                i.fa.fa-calendar.fa-2x
                = f.input :event_color, input_html: { type: "color" }, hint: "Wähle deine Farbe für die Konzerte im Kalender aus", label: false
              = f.input :id, as: :hidden, value: "#{current_user.id}"
            .text-center
              .button-group
                = f.submit "Ändern", class: "btn btn-secondary submit-button-band"
                = link_to band_path(@band), method: :delete, class: "btn btn-danger"
                  | Löschen
      .card-footer
        = simple_form_for :band_share, url: band_share_path do |b|
          .row
            .col.col-sm-6
              = b.select :user, options_from_collection_for_select(@users, "id", "name"), include_blank: 'Bandmitglied auswählen',class: "select_for_sharing_bands"
              = b.input :band_id, as: :hidden, input_html: { value: @band.id }
            .col.col-sm-6
              .text-center
                = b.submit "Teilen", class: "btn btn-secondary"
          .text-center
            small
              | Zum Teilen der Band, ein Bandmitglied auswählen. Dann werden die Kalendereinträge der Band mit den Bandmitgliedern geteilt.

app/views/bands/new.html.slim
= simple_form_for @band do |f|
  .text-band-edit-description style="margin-top: 2%"
    .card
      .card-body
        .custom_band_form
          .input-band-form-group
            i.fa.fa-user.fa-2x
            = f.input_field :name, required: true, placeholder: "Name", input_html: { required: true }, class: "band_name"
          .input-band-form-group
            i.fa.fa-map-marker.fa-2x
            = f.input_field :ort, placeholder: "Von wo kommt ihr her?"
          .input-band-form-group
            i.fa.fa-headphones.fa-2x
            = f.input_field :bandcamp, placeholder: "Bandcamp Link"
          .input-band-form-group
            i.fa.fa-home.fa-2x
            = f.input_field :website, placeholder: "Eure Website"
          .input-band-form-group
            i.fa.fa-envelope.fa-2x
            = f.input_field :email, required: true, placeholder: "Eure Band E-mail"
          .input-band-form-group
            i.fa.fa-phone.fa-2x
            = f.input_field :telefon, placeholder: "Telefon"
          .input-band-form-group
            i.fa.fa-birthday-cake.fa-2x
            = f.input :gründung, as: :date, html5: :true, label: false, hint: "Seit wann gibt es eure Band?"
          .input-band-form-group
            i.fa.fa-calendar.fa-2x
            = f.input :event_color, input_html: { type: "color" }, hint: "Wähle deine Farbe für die Konzerte im Kalender aus", label: false
        .text-center
          = f.submit "Abschicken", class: "btn btn-secondary submit-button-band"

app/views/bands/share.html.slim
p halloooo

app/views/bands/show.html.slim
.text-center
  = select_tag "Band", options_from_collection_for_select(@band, "id", "name"), include_blank: 'Band auswählen'

.js-lazy-load-band-edit
  .text-band-edit-description
    .card
      .card-body
        .card-title
          h4
            | Wähle deine Band aus um diese zu editieren.
        p
          | Deine eingegebenen Daten haben Einfluss darauf, was bei der Kontaktaufnahme mit dem Veranstalter angezeigt wird.
        p
          | So wird beispielsweise dein Bandcamp Link mit angegeben.

    .card-img-bottom
      = image_tag("einstellungen", class: "card-img-bottom")